### ISSUE TITLE
dm a notification reminder?

### ISSUE THREAD

**Issue by jonobrien** [Omodi/GoToBot#43]
ability to send a dm from bot to remind user about something

**Comment by Omodi** [comment]
slackbot does a great job of this already so I don't think we need it.  If you want to write it have fun but I'm going to close the issue.

**Comment by jonobrien** [comment]
haha I didn't even know

**Comment by Omodi** [comment]
It's /remind. I keep giving yura and derek tasks to complete

**Comment by jonobrien** [comment]
you can give reminders to other users? sounds spammy :+1:
